<a href="https://colab.research.google.com/github/jyjoon001/EEE4171/blob/main/PJ4/Aicomm_Project4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#initialize
import numpy as np
import pandas as pd

In [ ]:
#Matrix
H = np.matrix('0 0.5 0.5 0 0 0 0 0; 0.5 0 0 0 0.5 0 0 0; 0 0.5 0 0 0 0 0 0.5; 0 0 1 0 0 0 0 0; 0 0 0 0.5 0 0 0 0.5; 0 0 0 0.5 0.5 0 0 0; 0 0 0 0.5 0 0.5 0 0; 0.33333333 0 0 0.33333333 0 0 0.33333333 0') 
H

matrix([[0.        , 0.5       , 0.5       , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.5       , 0.        , 0.        , 0.        , 0.5       ,
         0.        , 0.        , 0.        ],
        [0.        , 0.5       , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.5       ],
        [0.        , 0.        , 1.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.5       , 0.        ,
         0.        , 0.        , 0.5       ],
        [0.        , 0.        , 0.        , 0.5       , 0.5       ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.5       , 0.        ,
         0.5       , 0.        , 0.        ],
        [0.33333333, 0.        , 0.        , 0.33333333, 0.        ,
         0.        , 0.33333333, 0.        ]])

In [ ]:
#Mandatory score-spreading
H_hat = H

In [ ]:
#Randomization
theta = 0.85
G = theta * H_hat + (1-theta)*(1/len(H))*np.ones((len(H),len(H)))
G

matrix([[0.01875   , 0.44375   , 0.44375   , 0.01875   , 0.01875   ,
         0.01875   , 0.01875   , 0.01875   ],
        [0.44375   , 0.01875   , 0.01875   , 0.01875   , 0.44375   ,
         0.01875   , 0.01875   , 0.01875   ],
        [0.01875   , 0.44375   , 0.01875   , 0.01875   , 0.01875   ,
         0.01875   , 0.01875   , 0.44375   ],
        [0.01875   , 0.01875   , 0.86875   , 0.01875   , 0.01875   ,
         0.01875   , 0.01875   , 0.01875   ],
        [0.01875   , 0.01875   , 0.01875   , 0.44375   , 0.01875   ,
         0.01875   , 0.01875   , 0.44375   ],
        [0.01875   , 0.01875   , 0.01875   , 0.44375   , 0.44375   ,
         0.01875   , 0.01875   , 0.01875   ],
        [0.01875   , 0.01875   , 0.01875   , 0.44375   , 0.01875   ,
         0.44375   , 0.01875   , 0.01875   ],
        [0.30208333, 0.01875   , 0.01875   , 0.30208333, 0.01875   ,
         0.01875   , 0.30208333, 0.01875   ]])

In [ ]:
#Iterations
iter = 10
pi = np.ones((len(G),1))*(1/len(G))
pi = pi.T
for i in range(0, iter):
    pi = pi*G
    print(pi.T);print('\n')

[[0.10729167]
 [0.125     ]
 [0.178125  ]
 [0.21354167]
 [0.125     ]
 [0.071875  ]
 [0.05416667]
 [0.125     ]]


[[0.10729167]
 [0.14005208]
 [0.24585937]
 [0.16085937]
 [0.10242187]
 [0.04177083]
 [0.05416667]
 [0.14757812]]


[[0.12008594]
 [0.16883919]
 [0.20107943]
 [0.14486654]
 [0.09602474]
 [0.04177083]
 [0.0605638 ]
 [0.16676953]]


[[0.13775802]
 [0.15524528]
 [0.19292308]
 [0.1503041 ]
 [0.10825926]
 [0.04448962]
 [0.06600137]
 [0.14501927]]


[[0.12581804]
 [0.15928947]
 [0.20505565]
 [0.15280765]
 [0.10363733]
 [0.04680058]
 [0.05983879]
 [0.14675249]]


[[0.1280279 ]
 [0.15937131]
 [0.20210916]
 [0.14969747]
 [0.10633827]
 [0.04418149]
 [0.06032987]
 [0.14994451]]


[[0.12896709]
 [0.15905825]
 [0.20040471]
 [0.15084537]
 [0.10525994]
 [0.0443902 ]
 [0.06123428]
 [0.14984016]]


[[0.12880447]
 [0.15873301]
 [0.20177958]
 [0.15083059]
 [0.10521559]
 [0.04477457]
 [0.06120471]
 [0.14865748]]


[[0.12833115]
 [0.15924822]
 [0.2016979 ]
 [0.15062744]
 [0.10524072]
 [0.044762

In [ ]:
pi.round(4)

array([[0.1287, 0.159 , 0.2013, 0.1507, 0.1055, 0.0446, 0.061 , 0.1492]])

In [ ]:
#PageRank result
import collections
pg = {k: v for v, k in enumerate(pi.round(4).tolist()[0])}
pg = collections.OrderedDict(sorted(pg.items(),reverse=True))
pg

OrderedDict([(0.2013, 2),
             (0.159, 1),
             (0.1507, 3),
             (0.1492, 7),
             (0.1287, 0),
             (0.1055, 4),
             (0.061, 6),
             (0.0446, 5)])

In [ ]:
print('The ranked order of the webpages are:')
for i in range(0, len(pg.values())):
    temp = list(pg.values())[i]+1
    print(temp)

The ranked order of the webpages are:
3
2
4
8
1
5
7
6
